---
title: "Read length and quality analysis"
author: "Jörg Wennmann"
date: "2024-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Required Libraries

```{r include=FALSE}
library(ggplot2)
library(ggrepel)
library(ShortRead)
library(RColorBrewer)
library(patchwork)
library(ggrepel)
```

# Required Functions

```{r}
phred_to_probability <- function(phred_scores) {
  probabilities <- 10^(-phred_scores / 10)
  probabilities <- 1-probabilities
  return(probabilities)
}

probability_to_phred <- function(probability) {
  phred_score <- -10 * log10(1 - probability)
  return(phred_score)
}

meanPhredScore <- function(qualities) {
  scores <- as.numeric(charToRaw(as.character(qualities))) - 33
  probabilities <- phred_to_probability(scores)
  probabilities <- mean(probabilities)
  scores <- probability_to_phred(probabilities)
  
  return(scores)
}

# Funktion zum Verarbeiten einer einzelnen FASTQ-Datei
process_fastq_file <- function(file_path) {
    fq <- readFastq(file_path)
    
    read_names <- as.character(id(fq))
    sequences <- sread(fq)
    qualities <- quality(fq)@quality
    
    read_lengths <- width(sequences)
    mean_quality_scores <- sapply(qualities, meanPhredScore)
    
    # Datei-Name ohne Suffix nach dem Punkt als Identifier
    iso_identifier <- sub("\\..*$", "", basename(file_path))
    
    data <- data.frame(
        Read_Name = read_names,
        Read_Length = read_lengths,
        Mean_Quality_Score = mean_quality_scores,
        Mean_Quality_Probability = phred_to_probability(mean_quality_scores),
        ISO = iso_identifier
    )
    
    return(data)
}
```


## Input data

### BmNPV + OrNV + WSSV

```{r}
# Pfad zur Ausgabe-Datei
input_file <- "data/read_length_quality/read_length_quality_df.csv"

# Überprüfen, ob die Datei bereits existiert
if (!file.exists(input_file)) {
    # Ordner mit den FASTQ-Dateien
    fastq_folder <- "input/raw reads"
    
    # Liste der FASTQ-Dateien im Ordner
    fastq_files <- list.files(fastq_folder, pattern = "\\.fastqsanger$", full.names = TRUE)
    
    # Initialisieren des Dataframes
    data <- data.frame()
    
    # Verarbeiten jeder Datei im Ordner und Hinzufügen der Ergebnisse zum Dataframe
    for (file in fastq_files) {
        file_data <- process_fastq_file(file)
        data <- rbind(data, file_data)
    }
    
    # Ausgabe des Dataframes
    print(data)
    
    # Speichern des Dataframes in einer CSV-Datei
    write.csv(data, input_file, row.names = FALSE)
} else {
    # Einlesen der vorhandenen CSV-Datei
    data <- read.csv(input_file)
    print("The input file already exists and has been read.")
    print(data)
}
```
### Combine read length data

```{r}
data$ISO <- gsub("^Th2$", "Nanopore: BmNPV-Th2", data$ISO)
data$ISO <- gsub("^Th15$", "Nanopore: BmNPV-Th15", data$ISO)
data$ISO <- gsub("^SRR21977634$", "Nanopore: OrNV-DUG42", data$ISO)
data$ISO <- gsub("^DRR420912_ref_CN01_filtered$", "Nanopore: WSSV-JP04", data$ISO)


data$ISO <- factor(data$ISO, levels = c("Nanopore: BmNPV-Th2", "Nanopore: BmNPV-Th15","Nanopore: OrNV-DUG42", "Nanopore: WSSV-JP04"))

data <- subset(data, ISO %in% c("Nanopore: BmNPV-Th2", "Nanopore: OrNV-DUG42", "Nanopore: WSSV-JP04"))
```

## Read length

### Nanopore data

```{r}
# Daten aufteilen
sep <- 60000

data_small <- subset(data, Read_Length < sep)
data_large <- subset(data, Read_Length >= sep)

# Gemeinsame Parameter
alpha <- 0.8

iso1Col <- brewer.pal(9, "Blues")[5]
iso2Col <- brewer.pal(9, "Greens")[5]
iso3Col <- c("#BC80BD")

fills <- c(iso1Col, iso2Col, iso3Col)

cols <- rep("black", length(unique(data$ISO))) 
binwidth <- 1000

# Plot für Reads bis 60.000
p1 <- ggplot(data_small) + 
  geom_histogram(aes(x = Read_Length, weight = Read_Length, fill = ISO, color = ISO), 
                 linewidth = 0.2, binwidth = binwidth, alpha = alpha) +
  scale_x_continuous(expand = c(0, 0),
                     breaks = seq(0, sep, by = 5000)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 30000000),
                     breaks = seq(0, 30000000, by = 2500000),
                     labels = seq(0, 30, by = 2.5)) +
  scale_fill_manual(values = alpha(fills, alpha)) +
  scale_color_manual(values = cols) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(0.7, 0.7),
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  ylab("Total Bases (Mb)") +
  xlab("Read Length (nt)")

# Plot für Reads >= 60.000
p2 <- ggplot(data_large) + 
  geom_histogram(aes(x = Read_Length, weight = Read_Length, fill = ISO, color = ISO), 
                 linewidth = 0.2, binwidth = binwidth, alpha = alpha) +
  scale_x_continuous(expand = c(0, 0),
                     breaks = seq(sep, 185000, by = 10000),
                     limits = c(sep,185000)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 900000),
                     breaks = seq(0, 900000, by = 100000),
                     labels = seq(0, 0.9, by = 0.1)) +
  scale_fill_manual(values = alpha(fills, alpha)) +
  scale_color_manual(values = cols) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  ylab("Total Bases (Mb)") +
  xlab("Read Length (nt)")


# Plots speichern
f <- 2

ggsave(plot = p1, filename = "output/read_length_distribution/length_distribution1.png", 
       units = "cm", 
       dpi = 300, 
       width = 6 * f, 
       height = 5 * f)

ggsave(plot = p2, filename = "output/read_length_distribution/length_distribution2.png", 
       units = "cm", 
       dpi = 300, 
       width = 6 * f, 
       height = 5 * f)


combined_plot <- (p1 + p2) + plot_annotation(tag_levels = 'A')

# Anzeige des kombinierten Plots
print(combined_plot)

f <- 0.8
# Speichern des kombinierten Plots als PDF
ggsave("output/read_length_distribution/length_distribution_combined.png", combined_plot, width = 12*f, height = 5*f) 

```

### PacBio data

```{r}
dataPB <- read.delim("data/read_length_quality/read_length_PacBio_AcMNPV.tabular", sep = "\t", header = FALSE)

colnames(dataPB) <- c("Read_Name", "Read_Length")

cutlength <- 50000

# Daten aufteilen
data_small <- subset(dataPB, Read_Length < cutlength)
data_large <- subset(dataPB, Read_Length >= cutlength)

# Gemeinsame Parameter
alpha <- 0.7
fills <- "firebrick1"
cols <- "black"
binwidth <- 1000

# Plot für Reads bis 60.000
pPB1 <- ggplot(data_small) + 
  geom_histogram(aes(x = Read_Length, weight = Read_Length, fill = fills), color = cols,
                 linewidth = 0.2, binwidth = binwidth, alpha = alpha) +
  scale_x_continuous(expand = c(0, 0),
                     breaks = seq(0, cutlength, by = 5000)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 1750000000),
                     breaks = seq(0, 1750000000, by = 250000000),
                     labels = seq(0, 17.5, by = 2.5)) +
  scale_fill_manual(values = alpha(fills, alpha), labels = "PacBio: AcMNPV-WP10") +
  scale_color_manual(values = cols) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(0.7, 0.9),
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  ylab("Total Bases (Gb)") +
  xlab("Read Length (nt)")



# Plot für Reads >= 60.000
last_bin_end <- max(data_large$Read_Length)

pPB2 <- ggplot(data_large) + 
  geom_histogram(aes(x = Read_Length, weight = Read_Length, fill = fills), color = cols,
                 linewidth = 0.2, binwidth = binwidth, alpha = alpha) +
  scale_x_continuous(expand = c(0, 0),
                     limits = c(cutlength, 87500),
                     breaks = seq(cutlength, 85000, by = 5000)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 7000000),
                     breaks = seq(0, 7000000, by = 1000000),
                     labels = seq(0, 7, by = 1)) +
  scale_fill_manual(values = alpha(fills, alpha)) +
  scale_color_manual(values = cols) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  ylab("Total Bases (Mb)") +
  xlab("Read Length (nt)")
  #annotate("text", x = last_bin_end - binwidth/2, y = 200000, label = "*", size = 8, color = "black", vjust = 0.05, hjust = 0.5)

# Plots anzeigen
print(pPB1)
print(pPB2)

# Plots speichern
f <- 2

ggsave(plot = pPB1, filename = "output/read_length_distribution/read_length_distributionPB1.png", 
       units = "cm", 
       dpi = 300, 
       width = 6 * f, 
       height = 5 * f)

ggsave(plot = pPB2, filename = "output/read_length_distribution/read_length_distributionPB2.png",  
       units = "cm", 
       dpi = 300, 
       width = 6 * f, 
       height = 5 * f)



combined_plot <- (pPB1 + pPB2) + plot_annotation(tag_levels = 'A')

# Anzeige des kombinierten Plots
print(combined_plot)

f <- 1.2

# Speichern des kombinierten Plots
ggsave("output/read_length_distribution/length_distribution_combined_PB.png", combined_plot, width = 8*f, height = 3*f)
```


# Read Quality Distribution

```{r}
alpha <- 0.8
# Calculate medians for each ISO group
medians <- aggregate(Mean_Quality_Score ~ ISO, data, median)
medians$Mean_Quality_Score <- round(medians$Mean_Quality_Score, 1)


#> unique(data$ISO)
#[1] Nanopore: OrNV-DUG42 Nanopore: BmNPV-Th2  Nanopore: WSSV-JP04 
#Levels: Nanopore: BmNPV-Th2 Nanopore: BmNPV-Th15 Nanopore: OrNV-DUG42 Nanopore: WSSV-JP04
data_iso1 <- subset(data, ISO == unique(data$ISO)[2])
data_iso2 <- subset(data, ISO == unique(data$ISO)[1])
data_iso3 <- subset(data, ISO == unique(data$ISO)[3])

# Create the histogram with customized axis labels-------------------------
max_x <- ceiling(max(data_iso1$Mean_Quality_Score) / 5) * 5
max_x <- 30
xbreaks <- sort(c(seq(0, max_x, by = 5), medians$Mean_Quality_Score[1], 9))
xbreaks <- xbreaks[xbreaks != 10]
xlabels <- sprintf("%.1f", xbreaks)

pQ1 <- ggplot() +
  geom_histogram(data = data_iso1, aes(x = Mean_Quality_Score), 
                 fill = brewer.pal(9, "Blues")[5],
                 linewidth = 0.2, 
                 binwidth = 1, 
                 color = "black", 
                 position = "identity", 
                 alpha = alpha) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  ylab("Frequency") +
  xlab("Median Read Quality Score (Q)") +
  scale_x_continuous(breaks = sort(xbreaks, decreasing = F),
                     labels = xlabels,
                     limits = c(0, max_x)) +
  scale_y_continuous(expand = c(0,0),
                     breaks = seq(0, 3000, by = 500), 
                     limits = c(0, 3000)) +
  geom_vline(aes(xintercept = medians$Mean_Quality_Score[1]), 
             linetype = "dashed", color = "black")



# Create the histogram with customized axis labels-------------------------
max_x <- 30
xbreaks <- sort(c(seq(0, max_x, by = 5), medians$Mean_Quality_Score[2]))
xbreaks <- xbreaks[xbreaks != 15]
xlabels <- sprintf("%.1f", xbreaks)

pQ2 <- ggplot() +
  geom_histogram(data = data_iso2, aes(x = Mean_Quality_Score), 
                 fill = brewer.pal(9, "Greens")[5],
                 linewidth = 0.2, 
                 binwidth = 1, 
                 color = "black", 
                 position = "identity", 
                 alpha = alpha) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  ylab("Frequency") +
  xlab("Median Read Quality Score (Q)") +
  scale_x_continuous(breaks = sort(xbreaks, decreasing = F),
                     labels = xlabels,
                     limits = c(0, max_x)) +
  scale_y_continuous(expand = c(0,0),
                     breaks = seq(0, 10000, by = 1000), 
                     limits = c(0, 10000)) +
  geom_vline(aes(xintercept = medians$Mean_Quality_Score[2]), 
             linetype = "dashed", color = "black")



# Create the histogram with customized axis labels-------------------------
max_x <- ceiling(max(data_iso3$Mean_Quality_Score) / 5) * 5
max_x <- 30
xbreaks <- sort(c(seq(0, max_x, by = 5), medians$Mean_Quality_Score[3], 14))
xbreaks <- xbreaks[xbreaks != 15]
xlabels <- sprintf("%.1f", xbreaks)

pQ3 <- ggplot() +
  geom_histogram(data = data_iso3, aes(x = Mean_Quality_Score), 
                 fill = "#BC80BD",
                 linewidth = 0.2, 
                 binwidth = 1, 
                 color = "black", 
                 position = "identity", 
                 alpha = alpha) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  ylab("Frequency") +
  xlab("Median Read Quality Score (Q)") +
  scale_x_continuous(breaks = sort(xbreaks, decreasing = F),
                     labels = xlabels,
                     limits = c(0, max_x)) +
  scale_y_continuous(expand = c(0,0),
                     breaks = seq(0, 5000, by = 500), 
                     limits = c(0, 5000)) +
  geom_vline(aes(xintercept = medians$Mean_Quality_Score[3]), linetype = "dashed", color = "black")



# saving Plots
f <- 2

ggsave(plot = pQ1, filename = "output/read_quality_distribution/read_quality_distribution_Th2.png", 
       units = "cm", 
       dpi = 300, 
       width = 6 * f, 
       height = 5 * f)

ggsave(plot = pQ2, filename = "output/read_quality_distribution/read_quality_distribution_OrNV.png", 
       units = "cm", 
       dpi = 300, 
       width = 6 * f, 
       height = 5 * f)

ggsave(plot = pQ3, filename = "output/read_quality_distribution/read_quality_distribution_WSSV.png", 
       units = "cm", 
       dpi = 300, 
       width = 6 * f, 
       height = 5 * f)

combined_plot <- (pQ1 + pQ2 + pQ3) +
  plot_annotation(tag_levels = 'A')

# Anzeige des kombinierten Plots
print(combined_plot)

f <- 0.8
# Speichern des kombinierten Plots als PDF
ggsave("output/read_quality_distribution/read_quality_distribution_combined.png", combined_plot, width = 12*f, height = 5*f)
```

# Read Length vs Quality


```{r}
thrQ1 <- medians$Mean_Quality_Score[1]
thrQ2 <- medians$Mean_Quality_Score[2]
thrQ3 <- medians$Mean_Quality_Score[3]

thrCol <- "black"

#Rechteck um Genome
top4 <- data_iso1[order(-data_iso1$Read_Length), ][1:4, ]
# Grenzen für das Rechteck berechnen
rect_xmin1 <- min(top4$Read_Length) - 2500
rect_xmax1 <- max(top4$Read_Length) + 2500
rect_ymin1 <- min(top4$Mean_Quality_Score) - 0.8
rect_ymax1 <- max(top4$Mean_Quality_Score) + 0.8

th2_half <- 63287.5
th2_full <- th2_half*2
xbreaks <- c(0, 10000, 20000, 30000, 40000, 50000, 63288,
            80000, 90000, 1e+05, 110000, 126575)

pLQ1 <- ggplot(data_iso1, aes(x = Read_Length, y = Mean_Quality_Score)) +
  geom_vline(xintercept = th2_full, linetype = "dotted", color = thrCol) +  # Vertikale Linie bei 60000
  geom_point(aes(color = (Read_Length > th2_half & Mean_Quality_Score > thrQ1)), alpha = 0.6) +
  scale_color_manual(values = c("TRUE" = "orange", "FALSE" = iso1Col)) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  ylab("Median Read Quality Score (Q)") +
  xlab("Read Length (nt)") +
  scale_x_continuous(expand = c(0,0),
                     #breaks = seq(0, 130000, by = 10000),
                     breaks = xbreaks,
                     limits = c(0, 140000)) +
  scale_y_continuous(expand = c(0,0),
                     breaks= sort(c(seq(0, 20, by = 5), thrQ1)), 
                     limits = c(0, 20)) +
  geom_vline(xintercept = th2_half, linetype = "dashed", color = thrCol) +
  geom_hline(yintercept = thrQ1, linetype = "dashed", color = thrCol) + 
  geom_rect(aes(xmin = rect_xmin1, xmax = rect_xmax1, ymin = rect_ymin1, ymax = rect_ymax1), 
            color = "black", fill = NA, size = 0.25)


#Rechteck um Genome
topNV <- data_iso2[order(-data_iso2$Read_Length), ][4:10, ]
# Grenzen für das Rechteck berechnen
rect_xmin2 <- min(topNV$Read_Length) - 2500
rect_xmax2 <- max(topNV$Read_Length) + 2500
rect_ymin2 <- min(topNV$Mean_Quality_Score) - 0.8
rect_ymax2 <- max(topNV$Mean_Quality_Score) + 0.8

dug42_half <- 62939.5
dug42_full <- dug42_half*2
xbreaks <- round(c(0, 20000, 40000, dug42_half, 80000, 1e+05, dug42_full, 140000, 160000, 
180769), digits = 0)

ybreaks <- sort(c(seq(5, 30, by = 5), thrQ2))
ybreaks <- ybreaks[ybreaks != 15]


pLQ2 <- ggplot(data_iso2, aes(x = Read_Length, y = Mean_Quality_Score)) +
  geom_point(aes(color = (Read_Length > dug42_half & Mean_Quality_Score > thrQ2)), alpha = 0.6) +
  scale_color_manual(values = c("TRUE" = "orange", "FALSE" = iso2Col)) +
  geom_vline(xintercept = dug42_full, linetype = "dotted", color = thrCol) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  ylab("Median Read Quality Score (Q)") +
  xlab("Read Length (nt)") +
  scale_x_continuous(expand = c(0,0),
                     breaks = xbreaks,
                     limits = c(0, 190000)) +
  scale_y_continuous(expand = c(0,0),
                     breaks= ybreaks,
                     limits = c(5, 30)) +
  geom_vline(xintercept = dug42_half, linetype = "dashed", color = thrCol) +  
  geom_hline(yintercept = thrQ2, linetype = "dashed", color = thrCol) + 
  geom_rect(aes(xmin = rect_xmin2, xmax = rect_xmax2, ymin = rect_ymin2, ymax = rect_ymax2), 
            color = "black", fill = NA, size = 0.25)  # Rechteck um alle vier Punkte


wssv_full <- 301054
wssv_half <- wssv_full/2
xbreaks <- c(0, 20000, 40000, 60000, 
80000, 100000, 120000, wssv_half, 171438, 180000)

ybreaks <- sort(c(seq(0, 25, by = 5), thrQ3, 14))
ybreaks <- ybreaks[ybreaks != 15]

pLQ3 <- ggplot(data_iso3, aes(x = Read_Length, y = Mean_Quality_Score)) +
  geom_point(aes(color = (Read_Length > wssv_half & Mean_Quality_Score > thrQ3)), 
             alpha = 0.6) +
  scale_color_manual(values = c("TRUE" = "orange", "FALSE" = "#BC80BD")) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  ylab("Median Read Quality Score (Q)") +
  xlab("Read Length (nt)") +
  scale_x_continuous(expand = c(0,0),
                     #breaks = seq(0, 130000, by = 10000),
                     breaks = xbreaks,
                     limits = c(0, 175000)) +
  scale_y_continuous(expand = c(0,0),
                     #breaks= sort(c(seq(0, 25, by = 5), thrQ3)), 
                     breaks = ybreaks,
                     limits = c(0, 25)) +
  geom_vline(xintercept = wssv_half, linetype = "dashed", color = thrCol) +  
  geom_hline(yintercept = thrQ3, linetype = "dashed", color = thrCol)  

# Plots speichern
f <- 2

ggsave(plot = pLQ1, filename = "output/read_length_vs_quality/read_length_vs_quality_Th2.png", 
       units = "cm", 
       dpi = 300, 
       width = 6 * f, 
       height = 5 * f)

ggsave(plot = pLQ2, filename = "output/read_length_vs_quality/read_length_vs_quality_OrNV.png", 
       units = "cm", 
       dpi = 300, 
       width = 6 * f, 
       height = 5 * f)

ggsave(plot = pLQ3, filename = "output/read_length_vs_quality/read_length_vs_quality_WSSV.png", 
       units = "cm", 
       dpi = 300, 
       width = 6 * f, 
       height = 5 * f)



combined_plot <- (pLQ1 + pLQ2 + pLQ3) +
  plot_annotation(tag_levels = 'A')

# Anzeige des kombinierten Plots
print(combined_plot)

f <- 0.8
# Speichern des kombinierten Plots als PDF
ggsave("output/read_length_vs_quality/read_length_vs_quality_combined.png", combined_plot, width = 12*f, height = 5*f)

```

# Combine all plots for publication

```{r}
combined_plot <- (p1 + p2) / (pQ1 + pQ2 + pQ3) / (pLQ1 + pLQ2 + pLQ3) / (pPB1 + pPB2) +
  plot_annotation(tag_levels = 'A')

# Anzeige des kombinierten Plots
print(combined_plot)

f <- 1.2
# Speichern des kombinierten Plots als PDF
ggsave("output/length_quality_plot_publication.png", combined_plot, width = 8*f, height = 10*f) 
```





